chat:
  system: |
    System: You are a Chat Bot.
    And return a json result about:
    {{
      "output":""
    }}
    This is the conversation history:
    {chat_history}
  user: |
    Reply the user chat message
    {input}